# Generated by Django 4.0.6 on 2022-12-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRates',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('eur', models.FloatField(blank=True, db_column='EUR', null=True)),
                ('usd', models.FloatField(blank=True, db_column='USD', null=True)),
                ('gbp', models.FloatField(blank=True, db_column='GBP', null=True)),
            ],
            options={
                'db_table': 'currency_rates',
                'ordering': ['date'],
                'managed': False,
            },
        ),
    ]
