# Generated by Django 4.0.6 on 2023-01-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphsApp', '0002_cryptocurrencies_stockexchange_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoCurrencies',
        ),
        migrations.DeleteModel(
            name='CurrencyRates',
        ),
        migrations.DeleteModel(
            name='StockExchange',
        ),
    ]
